#################################################
# Base configuration
#################################################



#################################################
# Platforms to test
#################################################


include:
  - '.gitlab-ci-files/job-android.yml'


stages:
 - build
 - deploy
